repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast

  - repo: local
    hooks:
      - id: unittests
        name: run make check test
        entry: make test
        language: system
        pass_filenames: false
      - id: format-check
        name: run make check format
        entry: make format-check
        language: system
        pass_filenames: false
      - id: type-check
        name: run make check type
        entry: make type-check
        language: system
        pass_filenames: false


      

