name: CI-Tests

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**'
      - 'src/pipeline/**'

# env:
#   AWS_DEFAULT_REGION: 'us-east-1'
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # - name: Install dependencies
      #   run: pip install pipenv && pipenv install --dev

      - name: Run Makefile
        run: make all      

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_DEFAULT_REGION }}

